### ISSUE TITLE
[BUG] Scrollbar rounded corners show fragments

### ISSUE THREAD

**Issue by Braweria** [Braweria/Spectrum#19]
```css
.workspace-split.mod-vertical.mod-root::-webkit-schollbar,
::-webkit-schollbar {
-webkit-border-radius: 0;
}
```

is what it should be.
