### ISSUE TITLE
[FEAT] Titlebar inner text should be hidden, so it doesn't collide with the quick explorer

### ISSUE THREAD

**Issue by Braweria** [Braweria/Spectrum#21]
```css
.titlebar-text {
 display: none;
}
```
