### ISSUE TITLE
fix blockquotes styling

### ISSUE THREAD

**Issue by Braweria** [Braweria/Spectrum#47]

**Comment by wobbba** [comment]
Not entirely sure what you mean and whether it is still relevant in 1.0.0 but I use this as a CSS snippet to make the callouts more to my liking:
```css
.callout {
    border:  2px solid #ffffff22;
    border-left: .3rem solid rgb(var(--callout-color));
    padding-top: 1rem;
}
```
If you want it to look like the old callouts, you could add
```css
.callout {
    background: #161616;
}
.callout::after {
    width: 100%;
    height: 3.25rem;
    background: rgb(var(--callout-color), 0.1);
    content: " ";
    position: absolute;
    left: 0;
    --callout-color: inherit;
    top: 0;
}
.callout-content {
    padding-top: 1rem;
}
```
Now that I actually look at it, I like that more than the new version, I'm gonna keep it, thanks for inspiring me :)

**Comment by wobbba** [comment]
What exactly do you mean? In edit or read mode? What do you want it to look like?

I first misread you question and wrote this CSS for callout style, don't want it to go to waste:
```css
.callout {
    background: #161616;
    border:  2px solid #ffffff22; /* remove this to make exactly like old version */
    border-left: .3rem solid rgb(var(--callout-color));
    padding-top: 1rem;
}
.callout::after {
    width: 100%;
    height: 3.25rem;
    background: rgb(var(--callout-color), 0.1);
    content: " ";
    position: absolute;
    left: 0;
    --callout-color: inherit;
    top: 0;
}
.callout-content {
    padding-top: 1rem;
}
```
It returns callouts to their old style.
