### ISSUE TITLE
[BUG] The headings lose colour when entering markdown preview mode in Obsidian

### ISSUE THREAD

**Issue by BrightBulb123** [Braweria/Spectrum#49]
**Describe the bug**
All `<h>` tags lose their special colours and switch to `--text-normal` when entering Markdown preview mode in Obsidian.

**To Reproduce**
1. Go to Obsidian
2. Update _Spectrum_
3. Type out a heading in a document (example: `# Heading 1`)
4. Enter `Reading Mode` (Markdown preview)

**Expected behavior**
It is expected for the headings to retain their colour (which works in live preview and source mode).

**Screenshots**

_No fix applied:_
![Source mode - no fix applied](https://user-images.githubusercontent.com/83759628/180096126-395f3f4d-c522-4615-a5b1-463025d6ec4b.png)
![Live preview - no fix applied](https://user-images.githubusercontent.com/83759628/180096172-c908dbde-c126-42d3-9626-5261674dfdf3.png)
![Reading mode (markdown preview) - no fix applied](https://user-images.githubusercontent.com/83759628/180096220-bc71f9f0-2418-4153-a190-6f5c8c39d7fd.png)

_Fix applied:_
![Reading mode (markdown preview) - fix applied](https://user-images.githubusercontent.com/83759628/180096359-6be1953a-6ae3-4fd5-84ae-f4bbcef82165.png)

**Desktop (please complete the following information):**
 - OS:

|  Property        | Value                                              |
|------------------|----------------------------------------------------|
| **Edition**      | Windows 10 Pro                                     |
| **Version**      | 21H2                                               |
| **Installed on** | ‎10/‎07/‎2021                                      |
| **OS build**     | 19044\.1826                                        |
| **Experience**   | Windows Feature Experience Pack 120\.2212\.4180\.0 |

 - Obsidian Version: v0.15.6 (Installer version: v0.14.6)

**Additional context**
I've found the problem to be missing `.markdown-preview-view` in each `.cm-header-...`. Example, here is the current code in `spectrum.css`:

```css
.cm-header-1,
h1 {
  color: var(--accent-1);
}

.cm-header-2,
h2 {
  color: var(--accent-2);
}

.cm-header-3,
h3 {
  color: var(--accent-3);
}

.cm-header-4,
h4 {
  color: var(--accent-4);
}

.cm-header-5,
h5 {
  color: var(--accent-5);
}

.cm-header-6,
.markdown-preview-view h6 {
  color: var(--accent-6);
}
```

I've found that by adding the `.markdown-preview-view` before each `h` tag, the issue is fixed. Example:

```css
.cm-header-1,
.markdown-preview-view h1 {
  color: var(--accent-1);
}

.cm-header-2,
.markdown-preview-view h2 {
  color: var(--accent-2);
}

.cm-header-3,
.markdown-preview-view h3 {
  color: var(--accent-3);
}

.cm-header-4,
.markdown-preview-view h4 {
  color: var(--accent-4);
}

.cm-header-5,
.markdown-preview-view h5 {
  color: var(--accent-5);
}

.cm-header-6,
.markdown-preview-view h6 {
  color: var(--accent-6);
}
```
