### ISSUE TITLE
Checklist Checkbox has two checkmarks

### ISSUE THREAD

**Issue by wobbba** [Braweria/Spectrum#52]
With the new 1.0 update the checkbox now has two checkmarks:
![image](https://user-images.githubusercontent.com/38957411/195828582-b4509b9f-7465-4399-854b-2fc1b4670146.png)

A working fix is to add custom CSS:
```css
input[type=checkbox]:checked:after {
  display: none;
}
```
