### ISSUE TITLE
Fix checkbox vertical position

### ISSUE THREAD

**Issue by wobbba** [Braweria/Spectrum#54]
Checkboxes (`- [ ]`) are not aligned correctly. I see that there are competing css rules for their `vertical-align`. A quick fix seems to be to just add more specificity to the overwritten rule, adding `.task-list-label` to the middle:
```css
.markdown-source-view.mod-cm6 .task-list-label .task-list-item-checkbox {
    vertical-align: baseline;
}
```
